sudo: required
dist: trusty
notifications:
- email:false
env:
- DROPBOX_OAUTH_BEARER="ajiHnDF-gfAAAAAAAAAAWrPPCDW77zh9g5UwjsZ6UrNes9Ldm9inK5mxul0FXqD3"
before_install:
# - sudo tlmgr install graphbox
- sudo apt-get install texlive-latex-recommended
- sudo apt-get install texlive-fonts-recommended
- sudo apt-get install texlive-latex-base
- sudo apt-get install texlive-base
- sudo apt-get install texlive-lang-italian
- sudo apt-get install texlive-latex-extra
# - sudo apt-get install xzdec
# - sudo mkdir /home/travis/texmf
# - sudo tlmgr init-usertree
# - sudo tlmgr install graphbox
# - sudo apt-get install texlive-full
# - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
- rvm install 2.2.6
- gem install dropbox-deployment
script:
- mkdir Docs
- mkdir Docs/RP

# ANALISI DEI REQUISITI
- cd ./RP/AnalisiDeiRequisiti/
- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v2.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v2.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v2.0.0.tex
- mv AnalisiDeiRequisiti_v2.0.0.pdf ../../Docs/RP
- cd ../..

# PAINO DI PROGETTO
- cd ./RP/PianoDiProgetto/
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v2.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v2.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v2.0.0.tex
- mv PianoDiProgetto_v2.0.0.pdf ../../Docs/RP
- cd ../..
after_success:
- dropbox-deployment