sudo: required
dist: trusty
notifications:
  slack:
    rooms:
    - sweeftyworkspace:B9YcyvwLNREWLqxH08sBAwzz
    template:
    - "Il *figlio di una puttana sieropositiva %{author}* ha rotto tutto il lavoro frutto di sudore e sangue del collettivo autistico _SWEefty_."
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    #on_success: always # default: always
    on_failure: always # default: always

env:
- DROPBOX_OAUTH_BEARER="ajiHnDF-gfAAAAAAAAAAWrPPCDW77zh9g5UwjsZ6UrNes9Ldm9inK5mxul0FXqD3"
before_install:
- sudo apt-get install texlive-latex-recommended
- sudo apt-get install texlive-fonts-recommended
- sudo apt-get install texlive-latex-base
- sudo apt-get install texlive-base
- sudo apt-get install texlive-lang-italian
- sudo apt-get install texlive-latex-extra
- rvm install 2.2.6
- gem install dropbox-deployment
script:
- mkdir Docs
- mkdir Docs/RQ
- mkdir Docs/RQ/Interni
- mkdir Docs/RQ/Interni/Verbali
- mkdir Docs/RQ/Esterni
- mkdir Docs/RQ/Esterni/Verbali

# ANALISI DEI REQUISITI
#- cd ./RQ/AnalisiDeiRequisiti/
#- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v3.0.0.tex
#- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v3.0.0.tex
#- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v3.0.0.tex
#- mv AnalisiDeiRequisiti_v3.0.0.pdf ../../Docs/RQ/Esterni
#- cd ../..

# GLOSSARIO
- cd ./RQ/Glossario/
- pdflatex -interaction=nonstopmode -halt-on-error Glossario_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error Glossario_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error Glossario_v3.0.0.tex
- mv Glossario_v3.0.0.pdf ../../Docs/RQ/Esterni
- cd ../..

# NORME DI PROGETTO
- cd ./RQ/NormeDiProgetto/
- pdflatex -interaction=nonstopmode -halt-on-error NormeDiProgetto_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error NormeDiProgetto_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error NormeDiProgetto_v3.0.0.tex
- mv NormeDiProgetto_v3.0.0.pdf ../../Docs/RQ/Interni
- cd ../..

# PIANO DI PROGETTO
- cd ./RQ/PianoDiProgetto/
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v4.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v4.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v4.0.0.tex
- mv PianoDiProgetto_v4.0.0.pdf ../../Docs/RQ/Esterni
- cd ../..

# PIANO DI QUALIFICA
- cd ./RQ/PianoDiQualifica/
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiQualifica_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiQualifica_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiQualifica_v3.0.0.tex
- mv PianoDiQualifica_v3.0.0.pdf ../../Docs/RQ/Esterni
- cd ../..

# PRODUCTBASELINE
- cd ./RQ/ProductBaseline/
- pdflatex -interaction=nonstopmode -halt-on-error ProductBaseline_v1.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error ProductBaseline_v1.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error ProductBaseline_v1.0.0.tex
- mv ProductBaseline_v1.0.0.pdf ../../Docs/RQ/Esterni
- cd ../..

# VERBALI INTERNI
- cd ./RQ/Verbali/Interni
#
- pdflatex -interaction=nonstopmode -halt-on-error VI_2017-12-07.tex
- pdflatex -interaction=nonstopmode -halt-on-error VI_2017-12-07.tex
- pdflatex -interaction=nonstopmode -halt-on-error VI_2017-12-07.tex
- mv VI_2017-12-07.pdf ../../../Docs/RQ/Interni/Verbali
#
- pdflatex -interaction=nonstopmode -halt-on-error VI_2017-12-20.tex
- pdflatex -interaction=nonstopmode -halt-on-error VI_2017-12-20.tex
- pdflatex -interaction=nonstopmode -halt-on-error VI_2017-12-20.tex
- mv VI_2017-12-20.pdf ../../../Docs/RQ/Interni/Verbali
# 
- pdflatex -interaction=nonstopmode -halt-on-error VI_2018-01-31.tex
- pdflatex -interaction=nonstopmode -halt-on-error VI_2018-01-31.tex
- pdflatex -interaction=nonstopmode -halt-on-error VI_2018-01-31.tex
# 
- pdflatex -interaction=nonstopmode -halt-on-error VI_2018-03-20.tex
- pdflatex -interaction=nonstopmode -halt-on-error VI_2018-03-20.tex
- pdflatex -interaction=nonstopmode -halt-on-error VI_2018-03-20.tex
- mv VI_2018-03-20.pdf ../../../Docs/RQ/Interni/Verbali
- mv VI_2018-03-20.pdf ../../../Docs/RQ/Interni/Verbali

- cd ../../..

## VERBALI ESTERNI
- cd ./RQ/Verbali/Esterni
#
- pdflatex -interaction=nonstopmode -halt-on-error VE_2017-12-06.tex
- pdflatex -interaction=nonstopmode -halt-on-error VE_2017-12-06.tex
- pdflatex -interaction=nonstopmode -halt-on-error VE_2017-12-06.tex
- mv VE_2017-12-06.pdf ../../../Docs/RQ/Esterni/Verbali
#
- pdflatex -interaction=nonstopmode -halt-on-error VE_2017-12-19.tex
- pdflatex -interaction=nonstopmode -halt-on-error VE_2017-12-19.tex
- pdflatex -interaction=nonstopmode -halt-on-error VE_2017-12-19.tex
- mv VE_2017-12-19.pdf ../../../Docs/RQ/Esterni/Verbali
# 
- pdflatex -interaction=nonstopmode -halt-on-error VE_2018-03-09.tex
- pdflatex -interaction=nonstopmode -halt-on-error VE_2018-03-09.tex
- pdflatex -interaction=nonstopmode -halt-on-error VE_2018-03-09.tex
- mv VE_2018-03-09.pdf ../../../Docs/RQ/Esterni/Verbali
#
- cd ../../..

after_success:
- dropbox-deployment
