sudo: required
dist: trusty
notifications:
- email:false
env:
- DROPBOX_OAUTH_BEARER="ajiHnDF-gfAAAAAAAAAAWrPPCDW77zh9g5UwjsZ6UrNes9Ldm9inK5mxul0FXqD3"
before_install:
# - sudo tlmgr install graphbox
- sudo apt-get install texlive-latex-recommended
- sudo apt-get install texlive-fonts-recommended
- sudo apt-get install texlive-latex-base
- sudo apt-get install texlive-base
- sudo apt-get install texlive-lang-italian
- sudo apt-get install texlive-latex-extra
- rvm install 2.2.6
- gem install dropbox-deployment
script:
- mkdir Docs
- mkdir Docs/RQ
- mkdir Docs/RQ/Interni
- mkdir Docs/RQ/Esterni
# aggiungere i verbali

# ANALISI DEI REQUISITI
- cd ./RQ/AnalisiDeiRequisiti/
- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error AnalisiDeiRequisiti_v3.0.0.tex
- mv AnalisiDeiRequisiti_v3.0.0.pdf ../../Docs/RQ/Esterni
- cd ../..

# GLOSSARIO
- cd ./RQ/Glossario/
- pdflatex -interaction=nonstopmode -halt-on-error Glossario_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error Glossario_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error Glossario_v3.0.0.tex
- mv Glossario_v3.0.0.pdf ../../Docs/RQ/Esterni
- cd ../..

# NORME DI PROGETTO
- cd ./RQ/NormeDiProgetto/
- pdflatex -interaction=nonstopmode -halt-on-error NormeDiProgetto_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error NormeDiProgetto_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error NormeDiProgetto_v3.0.0.tex
- mv NormeDiProgetto_v3.0.0.pdf ../../Docs/RQ/Interni
- cd ../..

# PIANO DI PROGETTO
- cd ./RQ/PianoDiProgetto/
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiProgetto_v3.0.0.tex
- mv PianoDiProgetto_v3.0.0.pdf ../../Docs/RQ/Esterni
- cd ../..

# PIANO DI QUALIFICA
- cd ./RQ/PianoDiQualifica/
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiQualifica_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiQualifica_v3.0.0.tex
- pdflatex -interaction=nonstopmode -halt-on-error PianoDiQualifica_v3.0.0.tex
- mv PianoDiQualifica_v3.0.0.pdf ../../Docs/RQ/Esterni
- cd ../..

after_success:
- dropbox-deployment